---
title: Evan Walters
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'I like developing

'
baseurl: "/"
url: https://evanwaltersdev.github.io/
permalink: "/:year/:month/:day/:title"
repository: evanwaltersdev/evanwaltersdev.github.io
paginate: 5
github_profile: https://github.com/evanwaltersdev.github.io
user: Evan Walters
user_email: evanwalters@protonmail.com
contact_url: mailto:evanwalters@protonmail.com
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-admin
exclude:
- Gemfile
- Gemfile.lock
sass:
  style: compressed
future: true
